use orca_core::runtime::Container;

/// Generate a `docker run` command from a container's config.
pub fn container_to_docker_run(container: &Container) -> String {
    let mut cmd = vec!["docker run -d".to_string()];

    // Name
    if !container.name.is_empty() {
        cmd.push(format!("--name {}", shell_escape(&container.name)));
    }

    // Ports
    for port in &container.ports {
        let host = if let Some(ref ip) = port.host_ip {
            format!("{}:{}:{}", ip, port.host_port, port.container_port)
        } else {
            format!("{}:{}", port.host_port, port.container_port)
        };
        if port.protocol != "tcp" {
            cmd.push(format!("-p {}/{}", host, port.protocol));
        } else {
            cmd.push(format!("-p {}", host));
        }
    }

    // Environment variables
    if let Some(env) = &container.env {
        for e in env {
            cmd.push(format!("-e {}", shell_escape(e)));
        }
    }

    // Mounts
    if let Some(mounts) = &container.mounts {
        for m in mounts {
            if m.rw {
                cmd.push(format!("-v {}:{}", shell_escape(&m.source), shell_escape(&m.destination)));
            } else {
                cmd.push(format!("-v {}:{}:ro", shell_escape(&m.source), shell_escape(&m.destination)));
            }
        }
    }

    // Restart policy from labels
    if let Some(policy) = container.labels.get("com.docker.compose.restart") {
        if policy != "no" {
            cmd.push(format!("--restart {policy}"));
        }
    }

    // Image
    cmd.push(shell_escape(&container.image));

    // Command
    if let Some(command) = &container.command {
        for arg in command {
            cmd.push(shell_escape(arg));
        }
    }

    cmd.join(" \\\n  ")
}

/// Generate a simple docker-compose.yml from a list of containers.
pub fn containers_to_compose(containers: &[Container], project_name: &str) -> String {
    let mut yaml = format!("# Generated by Orca\nname: {}\nservices:\n", project_name);

    for container in containers {
        let service_name = sanitize_service_name(&container.name);
        yaml.push_str(&format!("  {}:\n", service_name));
        yaml.push_str(&format!("    image: {}\n", container.image));

        if !container.ports.is_empty() {
            yaml.push_str("    ports:\n");
            for port in &container.ports {
                yaml.push_str(&format!(
                    "      - \"{}:{}\"\n",
                    port.host_port, port.container_port
                ));
            }
        }

        if let Some(env) = &container.env {
            if !env.is_empty() {
                yaml.push_str("    environment:\n");
                for e in env {
                    yaml.push_str(&format!("      - \"{}\"\n", e.replace('"', "\\\"")));
                }
            }
        }

        if let Some(mounts) = &container.mounts {
            if !mounts.is_empty() {
                yaml.push_str("    volumes:\n");
                for m in mounts {
                    if m.rw {
                        yaml.push_str(&format!("      - {}:{}\n", m.source, m.destination));
                    } else {
                        yaml.push_str(&format!("      - {}:{}:ro\n", m.source, m.destination));
                    }
                }
            }
        }

        if let Some(command) = &container.command {
            if !command.is_empty() {
                yaml.push_str(&format!(
                    "    command: [{}]\n",
                    command
                        .iter()
                        .map(|c| format!("\"{}\"", c.replace('"', "\\\"")))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
        }

        yaml.push('\n');
    }

    yaml
}

/// Shell-escape a string for use in a command line. Wraps in single quotes
/// if the string contains special characters.
fn shell_escape(s: &str) -> String {
    if s.is_empty() {
        return "''".to_string();
    }
    // If the string only contains safe chars, return as-is
    if s.chars()
        .all(|c| c.is_alphanumeric() || matches!(c, '-' | '_' | '.' | '/' | ':' | '=' | '@'))
    {
        return s.to_string();
    }
    // Wrap in single quotes, escaping any embedded single quotes
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// Sanitize a container name into a valid compose service name.
fn sanitize_service_name(name: &str) -> String {
    let sanitized: String = name
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if sanitized.is_empty() {
        "service".to_string()
    } else {
        sanitized
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use orca_core::runtime::{Container, ContainerState, PortMapping};
    use std::collections::HashMap;

    fn test_container() -> Container {
        Container {
            id: "abc123".to_string(),
            name: "my-app".to_string(),
            image: "nginx:latest".to_string(),
            state: ContainerState::Running,
            ports: vec![PortMapping {
                host_ip: None,
                host_port: 8080,
                container_port: 80,
                protocol: "tcp".to_string(),
            }],
            labels: HashMap::new(),
            created_at: "2024-01-01T00:00:00Z".to_string(),
            exit_code: None,
            error: None,
            oom_killed: None,
            started_at: None,
            finished_at: None,
            command: None,
            env: Some(vec!["FOO=bar".to_string()]),
            mounts: None,
        }
    }

    #[test]
    fn test_docker_run_output() {
        let c = test_container();
        let cmd = container_to_docker_run(&c);
        assert!(cmd.starts_with("docker run -d"));
        assert!(cmd.contains("--name my-app"));
        assert!(cmd.contains("-p 8080:80"));
        assert!(cmd.contains("-e FOO=bar"));
        assert!(cmd.contains("nginx:latest"));
    }

    #[test]
    fn test_compose_output() {
        let c = test_container();
        let yaml = containers_to_compose(&[c], "test-project");
        assert!(yaml.contains("name: test-project"));
        assert!(yaml.contains("image: nginx:latest"));
        assert!(yaml.contains("\"8080:80\""));
    }

    #[test]
    fn docker_run_with_empty_container() {
        let c = Container {
            id: String::new(),
            name: String::new(),
            image: "alpine".to_string(),
            state: ContainerState::Created,
            ports: vec![],
            labels: HashMap::new(),
            created_at: String::new(),
            exit_code: None,
            error: None,
            oom_killed: None,
            started_at: None,
            finished_at: None,
            command: None,
            env: None,
            mounts: None,
        };
        let cmd = container_to_docker_run(&c);
        assert!(cmd.starts_with("docker run -d"), "should start with docker run -d");
        assert!(cmd.contains("alpine"), "should contain the image name");
        // No --name flag when name is empty
        assert!(!cmd.contains("--name"), "should not have --name for empty name");
    }

    #[test]
    fn compose_with_special_chars_in_name() {
        let c = Container {
            id: "def456".to_string(),
            name: "my.app-v2".to_string(),
            image: "redis:7".to_string(),
            state: ContainerState::Running,
            ports: vec![],
            labels: HashMap::new(),
            created_at: String::new(),
            exit_code: None,
            error: None,
            oom_killed: None,
            started_at: None,
            finished_at: None,
            command: None,
            env: None,
            mounts: None,
        };
        let yaml = containers_to_compose(&[c], "test");
        // Dots and dashes should be replaced with underscores
        assert!(yaml.contains("my_app_v2:"), "dots/dashes should be sanitized to underscores");
        assert!(yaml.contains("image: redis:7"));
    }

    #[test]
    fn shell_escape_special_chars() {
        assert_eq!(shell_escape(""), "''");
        assert_eq!(shell_escape("simple"), "simple");
        assert_eq!(shell_escape("has space"), "'has space'");
        assert_eq!(shell_escape("it's"), "'it'\\''s'");
    }

    #[test]
    fn sanitize_service_name_empty() {
        assert_eq!(sanitize_service_name(""), "service");
    }

    #[test]
    fn sanitize_service_name_keeps_alphanumeric() {
        assert_eq!(sanitize_service_name("web_app1"), "web_app1");
    }
}
