use orca_core::templates::AppTemplate;

pub fn builtin_templates() -> Vec<AppTemplate> {
    vec![
        // Databases
        AppTemplate {
            id: "postgres".to_string(),
            name: "PostgreSQL".to_string(),
            description: "The world's most advanced open source relational database".to_string(),
            icon: "\u{1F418}".to_string(),
            category: "Database".to_string(),
            image: "postgres:16-alpine".to_string(),
            default_ports: vec!["5432:5432".to_string()],
            default_env: vec!["POSTGRES_PASSWORD=changeme".to_string(), "POSTGRES_DB=mydb".to_string()],
            default_volumes: vec!["pgdata:/var/lib/postgresql/data".to_string()],
            restart_policy: "unless-stopped".to_string(),
            notes: "Connect with: psql -h localhost -U postgres -d mydb".to_string(),
        },
        AppTemplate {
            id: "mysql".to_string(),
            name: "MySQL".to_string(),
            description: "Popular open source relational database".to_string(),
            icon: "\u{1F42C}".to_string(),
            category: "Database".to_string(),
            image: "mysql:8".to_string(),
            default_ports: vec!["3306:3306".to_string()],
            default_env: vec!["MYSQL_ROOT_PASSWORD=changeme".to_string(), "MYSQL_DATABASE=mydb".to_string()],
            default_volumes: vec!["mysqldata:/var/lib/mysql".to_string()],
            restart_policy: "unless-stopped".to_string(),
            notes: "Connect with: mysql -h 127.0.0.1 -u root -p".to_string(),
        },
        AppTemplate {
            id: "redis".to_string(),
            name: "Redis".to_string(),
            description: "In-memory data store, cache, and message broker".to_string(),
            icon: "\u{1F534}".to_string(),
            category: "Database".to_string(),
            image: "redis:alpine".to_string(),
            default_ports: vec!["6379:6379".to_string()],
            default_env: vec![],
            default_volumes: vec!["redisdata:/data".to_string()],
            restart_policy: "unless-stopped".to_string(),
            notes: "Connect with: redis-cli".to_string(),
        },
        AppTemplate {
            id: "mongodb".to_string(),
            name: "MongoDB".to_string(),
            description: "Document-oriented NoSQL database".to_string(),
            icon: "\u{1F343}".to_string(),
            category: "Database".to_string(),
            image: "mongo:7".to_string(),
            default_ports: vec!["27017:27017".to_string()],
            default_env: vec!["MONGO_INITDB_ROOT_USERNAME=admin".to_string(), "MONGO_INITDB_ROOT_PASSWORD=changeme".to_string()],
            default_volumes: vec!["mongodata:/data/db".to_string()],
            restart_policy: "unless-stopped".to_string(),
            notes: "Connect with: mongosh -u admin -p changeme".to_string(),
        },
        // Web Servers
        AppTemplate {
            id: "nginx".to_string(),
            name: "Nginx".to_string(),
            description: "High-performance web server and reverse proxy".to_string(),
            icon: "\u{1F310}".to_string(),
            category: "Web Server".to_string(),
            image: "nginx:alpine".to_string(),
            default_ports: vec!["8080:80".to_string()],
            default_env: vec![],
            default_volumes: vec![],
            restart_policy: "unless-stopped".to_string(),
            notes: "Serve files from /usr/share/nginx/html".to_string(),
        },
        AppTemplate {
            id: "caddy".to_string(),
            name: "Caddy".to_string(),
            description: "Fast web server with automatic HTTPS".to_string(),
            icon: "\u{1F512}".to_string(),
            category: "Web Server".to_string(),
            image: "caddy:alpine".to_string(),
            default_ports: vec!["80:80".to_string(), "443:443".to_string()],
            default_env: vec![],
            default_volumes: vec!["caddydata:/data".to_string(), "caddyconfig:/config".to_string()],
            restart_policy: "unless-stopped".to_string(),
            notes: "Configure via Caddyfile at /etc/caddy/Caddyfile".to_string(),
        },
        // Monitoring
        AppTemplate {
            id: "grafana".to_string(),
            name: "Grafana".to_string(),
            description: "Observability dashboards and visualization".to_string(),
            icon: "\u{1F4CA}".to_string(),
            category: "Monitoring".to_string(),
            image: "grafana/grafana:latest".to_string(),
            default_ports: vec!["3000:3000".to_string()],
            default_env: vec!["GF_SECURITY_ADMIN_PASSWORD=admin".to_string()],
            default_volumes: vec!["grafanadata:/var/lib/grafana".to_string()],
            restart_policy: "unless-stopped".to_string(),
            notes: "Login at http://localhost:3000 with admin/admin".to_string(),
        },
        AppTemplate {
            id: "prometheus".to_string(),
            name: "Prometheus".to_string(),
            description: "Monitoring and alerting toolkit".to_string(),
            icon: "\u{1F525}".to_string(),
            category: "Monitoring".to_string(),
            image: "prom/prometheus:latest".to_string(),
            default_ports: vec!["9090:9090".to_string()],
            default_env: vec![],
            default_volumes: vec!["promdata:/prometheus".to_string()],
            restart_policy: "unless-stopped".to_string(),
            notes: "Dashboard at http://localhost:9090".to_string(),
        },
        // Storage
        AppTemplate {
            id: "minio".to_string(),
            name: "MinIO".to_string(),
            description: "S3-compatible object storage".to_string(),
            icon: "\u{1F4BE}".to_string(),
            category: "Storage".to_string(),
            image: "minio/minio:latest".to_string(),
            default_ports: vec!["9000:9000".to_string(), "9001:9001".to_string()],
            default_env: vec!["MINIO_ROOT_USER=minioadmin".to_string(), "MINIO_ROOT_PASSWORD=minioadmin".to_string()],
            default_volumes: vec!["miniodata:/data".to_string()],
            restart_policy: "unless-stopped".to_string(),
            notes: "Console at http://localhost:9001".to_string(),
        },
        // Tools
        AppTemplate {
            id: "adminer".to_string(),
            name: "Adminer".to_string(),
            description: "Database management in a single PHP file".to_string(),
            icon: "\u{1F5C4}\u{FE0F}".to_string(),
            category: "Tools".to_string(),
            image: "adminer:latest".to_string(),
            default_ports: vec!["8081:8080".to_string()],
            default_env: vec![],
            default_volumes: vec![],
            restart_policy: "no".to_string(),
            notes: "Open http://localhost:8081 to manage databases".to_string(),
        },
        AppTemplate {
            id: "mailhog".to_string(),
            name: "MailHog".to_string(),
            description: "Email testing tool for developers".to_string(),
            icon: "\u{1F4E7}".to_string(),
            category: "Tools".to_string(),
            image: "mailhog/mailhog:latest".to_string(),
            default_ports: vec!["1025:1025".to_string(), "8025:8025".to_string()],
            default_env: vec![],
            default_volumes: vec![],
            restart_policy: "no".to_string(),
            notes: "SMTP on port 1025, Web UI at http://localhost:8025".to_string(),
        },
        AppTemplate {
            id: "portainer".to_string(),
            name: "Portainer".to_string(),
            description: "Container management UI".to_string(),
            icon: "\u{1F433}".to_string(),
            category: "Tools".to_string(),
            image: "portainer/portainer-ce:latest".to_string(),
            default_ports: vec!["9443:9443".to_string()],
            default_env: vec![],
            default_volumes: vec!["/var/run/docker.sock:/var/run/docker.sock".to_string(), "portainerdata:/data".to_string()],
            restart_policy: "unless-stopped".to_string(),
            notes: "Access at https://localhost:9443".to_string(),
        },
    ]
}
