//! Lima VM management — create, start, stop, delete Linux VMs on macOS.
//!
//! Uses the `limactl` CLI which wraps Apple's Virtualization.framework
//! (on ARM Macs) or QEMU (on Intel Macs).

use std::path::PathBuf;
use std::process::Stdio;

use tokio::process::Command;

use orca_core::machine::*;
use orca_core::runtime::RuntimeKind;

use crate::MacOSBackend;

/// Validate a machine/VM name. Must be safe to use as a filename fragment
/// and as an argv to limactl/wsl.
fn validate_vm_name(name: &str) -> anyhow::Result<()> {
    if name.is_empty() || name.len() > 64 {
        anyhow::bail!("VM name must be 1..=64 characters");
    }
    if name.starts_with('-') || name.starts_with('.') {
        anyhow::bail!("VM name must not start with '-' or '.'");
    }
    if !name
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_'))
    {
        anyhow::bail!("VM name must contain only ASCII alphanumerics, '-', and '_'");
    }
    Ok(())
}

impl MachineManager for MacOSBackend {
    async fn create(&self, config: MachineConfig) -> anyhow::Result<MachineInfo> {
        validate_vm_name(&config.name)?;
        // Reject nonsensical resource values before templating so limactl
        // doesn't bail with a cryptic error.
        if config.cpus == 0 {
            anyhow::bail!("cpus must be >= 1");
        }
        if config.memory_mb < 1024 {
            anyhow::bail!("memory_mb must be >= 1024");
        }
        if config.disk_gb < 10 {
            anyhow::bail!("disk_gb must be >= 10");
        }
        let runtime_pkg = match config.runtime {
            RuntimeKind::Podman => "podman",
            RuntimeKind::Docker => "docker",
        };

        // Generate a Lima YAML config
        let lima_config = format!(
            r#"# Generated by Orca
vmType: "vz"
rosetta:
  enabled: true
  binfmt: true
cpus: {cpus}
memory: "{memory}GiB"
disk: "{disk}GiB"
mountType: "virtiofs"
mounts:
  - location: "~"
    writable: true
  - location: "/tmp/lima"
    writable: true
containerd:
  system: false
  user: false
provision:
  - mode: system
    script: |
      #!/bin/bash
      # pipefail so `curl | sh` propagates a curl failure — without it a
      # DNS/TLS failure on get.docker.com is silently ignored and the VM
      # boots "successfully" with no Docker installed.
      set -euo pipefail

      # Install container runtime
      if ! command -v {runtime_pkg} &> /dev/null; then
        if [ "{runtime_pkg}" = "podman" ]; then
          apt-get update -qq && apt-get install -y -qq podman
        else
          # Download the installer first so we can propagate download
          # failures before executing.
          curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
          sh /tmp/get-docker.sh
          rm -f /tmp/get-docker.sh
          usermod -aG docker $LIMA_CIDATA_USER
        fi
      fi

      # Set up host.docker.internal DNS
      # Lima provides the host gateway at 192.168.5.2
      HOST_IP=$(ip route | awk '/default/{{print $3}}')
      if ! grep -q host.docker.internal /etc/hosts; then
        echo "$HOST_IP host.docker.internal host.lima.internal" >> /etc/hosts
      fi

      # Install HWE kernel for idmapped mount support (requires 6.12+)
      # This gives us transparent UID remapping on VirtioFS mounts
      if ! dpkg -l linux-generic-hwe-24.04 2>/dev/null | grep -q ^ii; then
        apt-get update -qq && apt-get install -y -qq linux-generic-hwe-24.04
      fi
portForwards:
  # Forward the Docker/Podman socket
  - guestSocket: "/var/run/docker.sock"
    hostSocket: "{{{{.Dir}}}}/sock/docker.sock"
  # Forward all Docker container ports (bound to 0.0.0.0) to localhost on host
  - guestIP: "0.0.0.0"
    guestIPMustBeZero: true
    guestPortRange: [1, 65535]
    hostIP: "127.0.0.1"
    proto: tcp
hostResolver:
  enabled: true
  hosts:
    host.docker.internal: host.lima.internal
propagateProxyEnv: true
"#,
            cpus = config.cpus,
            memory = config.memory_mb / 1024,
            disk = config.disk_gb,
            runtime_pkg = runtime_pkg,
        );

        // Use a unique, locally-created temp file so a local attacker can't
        // pre-create a symlink at a predictable `/tmp/orca-<name>.yaml`
        // path and have the Lima config written through the symlink.
        let tmp = tempfile::Builder::new()
            .prefix("orca-lima-")
            .suffix(".yaml")
            .tempfile()?;
        tokio::fs::write(tmp.path(), &lima_config).await?;
        let config_path = tmp.path().to_path_buf();

        let output = limactl_cmd()
            .args([
                "create",
                "--name",
                &config.name,
                config_path
                    .to_str()
                    .ok_or_else(|| anyhow::anyhow!("Invalid config path"))?,
            ])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("Failed to create Lima VM: {stderr}");
        }

        let _ = tokio::fs::remove_file(&config_path).await;

        self.inspect(&config.name).await
    }

    async fn start(&self, name: &str) -> anyhow::Result<()> {
        validate_vm_name(name)?;
        let output = limactl_cmd()
            // `--` separates options from positional names so a future
            // limactl version that adds a flag starting like our name
            // can't misinterpret it. Only `create` accepts a YAML path;
            // start/stop/kill/delete/inspect all take VM names after --.
            .args(["start", "--", name])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("Failed to start VM '{name}': {stderr}");
        }
        Ok(())
    }

    async fn stop(&self, name: &str) -> anyhow::Result<()> {
        validate_vm_name(name)?;
        let output = limactl_cmd()
            .args(["stop", "--", name])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("Failed to stop VM '{name}': {stderr}");
        }
        Ok(())
    }

    async fn kill(&self, name: &str) -> anyhow::Result<()> {
        validate_vm_name(name)?;
        let output = limactl_cmd()
            .args(["stop", "--force", "--", name])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("Failed to kill VM '{name}': {stderr}");
        }
        Ok(())
    }

    async fn delete(&self, name: &str) -> anyhow::Result<()> {
        validate_vm_name(name)?;
        // Stop first if running — log any failure so a stuck VM
        // manifests as something more actionable than a cryptic
        // "limactl delete" error later on.
        if let Err(e) = self.stop(name).await {
            tracing::warn!("Lima delete: stop('{name}') failed (continuing): {e}");
        }

        let output = limactl_cmd()
            .args(["delete", "--", name])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("Failed to delete VM '{name}': {stderr}");
        }
        Ok(())
    }

    async fn inspect(&self, name: &str) -> anyhow::Result<MachineInfo> {
        validate_vm_name(name)?;
        let output = limactl_cmd()
            .args(["list", "--json"])
            .stdout(Stdio::piped())
            .output()
            .await?;

        let stdout = String::from_utf8_lossy(&output.stdout);

        // limactl list --json outputs one JSON object per line
        for line in stdout.lines() {
            if let Ok(vm) = serde_json::from_str::<serde_json::Value>(line)
                && vm.get("name").and_then(|n| n.as_str()) == Some(name)
            {
                return Ok(parse_lima_vm(&vm));
            }
        }

        anyhow::bail!("VM '{name}' not found")
    }

    async fn list(&self) -> anyhow::Result<Vec<MachineInfo>> {
        let output = limactl_cmd()
            .args(["list", "--json"])
            .stdout(Stdio::piped())
            .output()
            .await?;

        let stdout = String::from_utf8_lossy(&output.stdout);
        let mut machines = Vec::new();

        for line in stdout.lines() {
            if let Ok(vm) = serde_json::from_str::<serde_json::Value>(line) {
                machines.push(parse_lima_vm(&vm));
            }
        }

        Ok(machines)
    }

    async fn runtime_socket(&self, _name: &str) -> anyhow::Result<PathBuf> {
        Ok(self.socket_path.clone())
    }
}

/// Build a `Command::new("limactl")` with proxy env vars scrubbed.
///
/// The Lima template sets `propagateProxyEnv: true`, which means Lima
/// reads `HTTP_PROXY`/`HTTPS_PROXY`/`NO_PROXY` from whatever environment
/// started the daemon and propagates them into the guest — where the
/// `curl https://get.docker.com | sh` bootstrap then uses them. A
/// poisoned proxy env var on the daemon host would therefore end up
/// routing the Docker installer download through an attacker-controlled
/// proxy. Remove these variables from every limactl invocation so the
/// value the daemon sees never leaks into the VM image.
fn limactl_cmd() -> Command {
    let mut cmd = Command::new("limactl");
    cmd.env_remove("HTTP_PROXY")
        .env_remove("HTTPS_PROXY")
        .env_remove("http_proxy")
        .env_remove("https_proxy")
        .env_remove("NO_PROXY")
        .env_remove("no_proxy");
    cmd
}

fn parse_lima_vm(vm: &serde_json::Value) -> MachineInfo {
    let name = vm.get("name").and_then(|n| n.as_str()).unwrap_or("unknown").to_string();

    let status = vm.get("status").and_then(|s| s.as_str()).unwrap_or("Unknown");

    let state = match status {
        "Running" => MachineState::Running,
        "Stopped" => MachineState::Stopped,
        _ => MachineState::Error,
    };

    let cpus = vm.get("cpus").and_then(|c| c.as_u64()).unwrap_or(0) as u32;
    let memory = vm.get("memory").and_then(|m| m.as_u64()).unwrap_or(0) / (1024 * 1024); // bytes to MB
    let disk = vm.get("disk").and_then(|d| d.as_u64()).unwrap_or(0) / (1024 * 1024 * 1024); // bytes to GB

    MachineInfo {
        name: name.clone(),
        state,
        config: MachineConfig {
            name,
            cpus,
            memory_mb: memory,
            disk_gb: disk,
            runtime: RuntimeKind::Docker,
            mounts: vec![],
        },
        backend: MachineBackend::Lima,
    }
}
