//! Lima VM management — create, start, stop, delete Linux VMs on macOS.
//!
//! Uses the `limactl` CLI which wraps Apple's Virtualization.framework
//! (on ARM Macs) or QEMU (on Intel Macs).

use std::path::PathBuf;
use std::process::Stdio;

use tokio::process::Command;

use orca_core::machine::*;
use orca_core::runtime::RuntimeKind;

use crate::MacOSBackend;

impl MachineManager for MacOSBackend {
    async fn create(&self, config: MachineConfig) -> anyhow::Result<MachineInfo> {
        let runtime_pkg = match config.runtime {
            RuntimeKind::Podman => "podman",
            RuntimeKind::Docker => "docker",
        };

        // Generate a Lima YAML config
        let lima_config = format!(
            r#"# Generated by Orca
vmType: "vz"
rosetta:
  enabled: true
  binfmt: true
cpus: {cpus}
memory: "{memory}GiB"
disk: "{disk}GiB"
mountType: "virtiofs"
mounts:
  - location: "~"
    writable: true
  - location: "/tmp/lima"
    writable: true
containerd:
  system: false
  user: false
provision:
  - mode: system
    script: |
      #!/bin/bash
      if ! command -v {runtime_pkg} &> /dev/null; then
        if [ "{runtime_pkg}" = "podman" ]; then
          apt-get update -qq && apt-get install -y -qq podman
        else
          curl -fsSL https://get.docker.com | sh
          usermod -aG docker $LIMA_CIDATA_USER
        fi
      fi
portForwards:
  - guestSocket: "/var/run/docker.sock"
    hostSocket: "{{{{.Dir}}}}/sock/docker.sock"
"#,
            cpus = config.cpus,
            memory = config.memory_mb / 1024,
            disk = config.disk_gb,
            runtime_pkg = runtime_pkg,
        );

        let config_path = std::env::temp_dir().join(format!("orca-{}.yaml", config.name));
        tokio::fs::write(&config_path, &lima_config).await?;

        let output = Command::new("limactl")
            .args(["create", "--name", &config.name, config_path.to_str().unwrap()])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("Failed to create Lima VM: {stderr}");
        }

        let _ = tokio::fs::remove_file(&config_path).await;

        self.inspect(&config.name).await
    }

    async fn start(&self, name: &str) -> anyhow::Result<()> {
        let output = Command::new("limactl")
            .args(["start", name])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("Failed to start VM '{name}': {stderr}");
        }
        Ok(())
    }

    async fn stop(&self, name: &str) -> anyhow::Result<()> {
        let output = Command::new("limactl")
            .args(["stop", name])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("Failed to stop VM '{name}': {stderr}");
        }
        Ok(())
    }

    async fn kill(&self, name: &str) -> anyhow::Result<()> {
        let output = Command::new("limactl")
            .args(["stop", "--force", name])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("Failed to kill VM '{name}': {stderr}");
        }
        Ok(())
    }

    async fn delete(&self, name: &str) -> anyhow::Result<()> {
        // Stop first if running
        let _ = self.stop(name).await;

        let output = Command::new("limactl")
            .args(["delete", name])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("Failed to delete VM '{name}': {stderr}");
        }
        Ok(())
    }

    async fn inspect(&self, name: &str) -> anyhow::Result<MachineInfo> {
        let output = Command::new("limactl")
            .args(["list", "--json"])
            .stdout(Stdio::piped())
            .output()
            .await?;

        let stdout = String::from_utf8_lossy(&output.stdout);

        // limactl list --json outputs one JSON object per line
        for line in stdout.lines() {
            if let Ok(vm) = serde_json::from_str::<serde_json::Value>(line) {
                if vm.get("name").and_then(|n| n.as_str()) == Some(name) {
                    return Ok(parse_lima_vm(&vm));
                }
            }
        }

        anyhow::bail!("VM '{name}' not found")
    }

    async fn list(&self) -> anyhow::Result<Vec<MachineInfo>> {
        let output = Command::new("limactl")
            .args(["list", "--json"])
            .stdout(Stdio::piped())
            .output()
            .await?;

        let stdout = String::from_utf8_lossy(&output.stdout);
        let mut machines = Vec::new();

        for line in stdout.lines() {
            if let Ok(vm) = serde_json::from_str::<serde_json::Value>(line) {
                machines.push(parse_lima_vm(&vm));
            }
        }

        Ok(machines)
    }

    async fn runtime_socket(&self, _name: &str) -> anyhow::Result<PathBuf> {
        Ok(self.socket_path.clone())
    }
}

fn parse_lima_vm(vm: &serde_json::Value) -> MachineInfo {
    let name = vm
        .get("name")
        .and_then(|n| n.as_str())
        .unwrap_or("unknown")
        .to_string();

    let status = vm
        .get("status")
        .and_then(|s| s.as_str())
        .unwrap_or("Unknown");

    let state = match status {
        "Running" => MachineState::Running,
        "Stopped" => MachineState::Stopped,
        _ => MachineState::Error,
    };

    let cpus = vm
        .get("cpus")
        .and_then(|c| c.as_u64())
        .unwrap_or(0) as u32;
    let memory = vm
        .get("memory")
        .and_then(|m| m.as_u64())
        .unwrap_or(0)
        / (1024 * 1024); // bytes to MB
    let disk = vm
        .get("disk")
        .and_then(|d| d.as_u64())
        .unwrap_or(0)
        / (1024 * 1024 * 1024); // bytes to GB

    MachineInfo {
        name: name.clone(),
        state,
        config: MachineConfig {
            name,
            cpus,
            memory_mb: memory,
            disk_gb: disk,
            runtime: RuntimeKind::Docker,
            mounts: vec![],
        },
        backend: MachineBackend::Lima,
    }
}
